# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to s3

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

        
    - name: Install dependencies
      working-directory: html
      run: npm ci   

    - name: Build project
      working-directory: html
      run: npm run build --if-present


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: us-east-1

    - name: Sync build folder to S3
      run: |
        aws s3 sync html/dist/ s3://weatheralertsapp --delete

    - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_CF_DISTRO }} --paths "/*"

    
